version: '3.9'

services:
  stock-online-app:
    container_name: stock-online-app
    build:
      context: stock-online
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - stock-network
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATA_REDIS_HOST=stock-redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TOPIC_STOCK-DECREASE=stock-decrease
      - SPRING_DATA_REDIS_TOPIC_STOCK-RESTORE=stock-restore
    depends_on:
      stock-db:
        condition: service_healthy
      stock-redis:
        condition: service_started

  ## mysql
  stock-db:
    image: mysql:latest
    container_name: stock-db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stock-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stock
      - MYSQL_USER=stock
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ## redis
  stock-redis:
    image: redis:7.4.2
    container_name: stock-redis
    ports:
      - "6379:6379"
    networks:
      - stock-network
    volumes:
      - redis-data:/var/lib/redis

networks:
  stock-network:
    name: stock-network
    driver: bridge

volumes:
  db-data:
  redis-data:
